version: 2

updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "npm"
    rebase-strategy: auto
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Kolkata"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: ":arrow_up: "

  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    rebase-strategy: auto
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: ":arrow_up: "
