repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      # - id: no-commit-to-branch
      #   args: ["--branch", "main", "--branch", "release", "--branch", "staging"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        stages: [pre-commit]
        name: check for non-standard formatting concerns
        additional_dependencies:
          - prettier@3
          - "@trivago/prettier-plugin-sort-imports"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        stages: [pre-commit]
        name: check for linting errors and warnings
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8
          - eslint-config-prettier
          - eslint-config-next

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        name: lint commit messages
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
