repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        name: lint commit messages
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.7
    hooks:
      - id: prettier
        name: format frontend source code
        additional_dependencies:
          - "prettier"
          - "prettier-plugin-astro"
        stages:
          - pre-commit
        types:
          - ts
          - javascript
          - markdown
          # FIXME: Not suppported for now!
          # - astro
          - css
          - javascript

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        name: lint frontend source code
        additional_dependencies:
          - eslint
          - "@typescript-eslint/parser"
          - "eslint-plugin-astro"
          - "eslint-plugin-jsx-a11y"
        types:
          - ts
          # FIXME: Not suppported for now!
          # - astro
          - javascript

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.85.0
    hooks:
      - id: terraform_fmt
        name: format Terraform code
