name: Code QA

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
      - review_requested
    paths: [website/**]
    branches-ignore: [dependabot/**]

jobs:
  linter:
    name: Run Oxlint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@v2.1.0
        with:
          working-directory: ./website
          cache: true
          require-lockfile: true

      - name: Run Formatters
        run: pnpm run lint

  formatter:
    name: Run Oxfmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@v2.1.0
        with:
          working-directory: ./website
          cache: true
          require-lockfile: true

      - name: Run Formatters
        run: pnpm run fmt:check

  build:
    name: Build site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@v2.1.0
        with:
          working-directory: ./website
          cache: true
          require-lockfile: true

      - name: Build the site
        run: pnpm run generate
