name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
      - "dependabot/**"

jobs:
  code-quality-checks:
    name: Code QA Checks

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js in the Runtime
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          cache: "npm"

      - name: Install the Dependencies
        run: npm ci

      - name: Run Code Quality Checks
        run: npm run lint

      - name: Run Prettier to Check for Formatting Issues
        run: npm run format

  deploy-preview:
    name: Preview Deployment

    runs-on: ubuntu-latest

    environment: Preview

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
