name: Production Deployment

on:
  release:
    types: [published, released]

jobs:
  code-quality-checks:
    name: Code QA Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install the Dependencies
        run: npm ci

      - name: Run Code Quality Checks
        run: npm run lint

      - name: Run Prettier to Check for Formatting Issues
        run: npm run format:check

  deploy-production:
    name: Production Deployment
    defaults:
      run:
        working-directory: ./terraform
    runs-on: ubuntu-latest
    needs: code-quality-checks
    environment:
      name: Production
      # FIXME: Update the URL to be dynamically fetched by Terraform
      url: https://jarmos.dev
    env:
      PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: Initialise the Environment for Terraform
        run: terraform init -input=false

      - name: Deploy to Production
        run: |
          terraform plan -var "vercel_api_token=${VERCEL_API_TOKEN}" -out=tfplan -input=false
          terraform apply -input=false tfplan
